driver:
  require_chef_omnibus: <%= ENV.fetch("CHEF_VERSION", "latest") %>
  ssh_key: <%= File.expand_path("./test/support/keys/vagrant") %>
  name: vagrant
  customize:
    memory: 768

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: client
    run_list:
      - recipe[percona::client]
  - name: server
    run_list:
      - recipe[percona::server]
    attributes:
      percona:
        server:
          jemalloc: true
          debian_password: d3b1an
          root_password: r00t
  - name: xtrabackup
    run_list:
      - recipe[percona::server]
      - recipe[percona::backup]
  - name: toolkit
    run_list:
      - recipe[percona::toolkit]
  - name: new_datadir
    run_list:
      - recipe[percona::server]
    attributes:
      percona:
        server:
          datadir: "/tmp/mysql"
